// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpQYRM3cfjMYL--9xMMZ8fie32Z3ubvRY',
    appId: '1:251473824582:web:5551b5b3c80e7bd75d3347',
    messagingSenderId: '251473824582',
    projectId: 'campusproedtech',
    authDomain: 'campusproedtech.firebaseapp.com',
    storageBucket: 'campusproedtech.appspot.com',
    measurementId: 'G-79KWN6CGD2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmOxAZx9dMN3vyEvpbnIcQDlexLUQJuyA',
    appId: '1:251473824582:android:d60f31b2263bb06b5d3347',
    messagingSenderId: '251473824582',
    projectId: 'campusproedtech',
    storageBucket: 'campusproedtech.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwbjgn3vzR8sJ1-PmWpwMsFhXAGjHuaKs',
    appId: '1:251473824582:ios:9606ca1b300266fb5d3347',
    messagingSenderId: '251473824582',
    projectId: 'campusproedtech',
    storageBucket: 'campusproedtech.appspot.com',
    iosBundleId: 'com.campuspro.campuspro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwbjgn3vzR8sJ1-PmWpwMsFhXAGjHuaKs',
    appId: '1:251473824582:ios:aeda24acb77dde6b5d3347',
    messagingSenderId: '251473824582',
    projectId: 'campusproedtech',
    storageBucket: 'campusproedtech.appspot.com',
    iosBundleId: 'com.campuspro.campurProEdtech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpQYRM3cfjMYL--9xMMZ8fie32Z3ubvRY',
    appId: '1:251473824582:web:4043396911a86b025d3347',
    messagingSenderId: '251473824582',
    projectId: 'campusproedtech',
    authDomain: 'campusproedtech.firebaseapp.com',
    storageBucket: 'campusproedtech.appspot.com',
    measurementId: 'G-D37M6HGYX6',
  );
}
